name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Delete merged branch
      uses: SvanBoxel/delete-merged-branch@v1.3.3
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
